title: Manuel Razo-Mejia  
description: > # this means to ignore newlines until "baseurl:"
  Manuel Razo-Mejia personal website.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Manuel Razo-Mejia # add your name
author-img: manuel_razo.jpg # add your photo
about-author: I am a graduate student @Caltech working in the interface between physics, biology, and evolution. # add description
social-twitter: mrazomej # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: mrazomej # add your Github handle
# social-linkedin: # add your Linkedin handle
social-email: mrazomej@caltech.edu # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
