# website settings
website:
  # Name
  title: "Manuel Razo-Mejia, Ph.D."
  # A brief slogan (optional)
  description: "Postdoctoral Scholar, Stanford University"
  # Image for the website
  image: img/manuel_razo.jpg
  # Icon for the website
  favicon: img/darwin_tree.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png

    # sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Software"
        href: software/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Media"
        href: media/index.qmd
    
    # social media handles
    right:
      - icon: github
        href: https://github.com/mrazomej
      - icon: twitter-x
        href: https://twitter.com/mrazomej
      - icon: linkedin
        href: https://www.linkedin.com/in/manuel-razo-mejia-506b4a148/
      # - icon: envelope
      #   aria-label: email
      #   href: "mailto:mail.marvinschmitt@gmail.com"  
  
  
  

  # Set navigation bar
  search: 
    location: navbar
    type: textbox
  # Set page-footer 
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Manuel Razo-Mejia CC BY-SA 4.0</span>
    # center: |
    #   <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
    # right: |
    #   <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

# Define project type
project:
  # Define project as a website
  type: website
  # Define output directory
  output-dir: docs

  # Set preview options
  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

# Define output format
format:
  # Define HTML output
  html:
    # Define fontsize: 
    fontsize: 1.1em
    # Define two themes: light and dark
    theme: 
      light:
        - flatly
        - html/style.scss
      dark:
        - darkly
        - html/style.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true