---
title: Publications
---

### *Preprints*

### *Peer-reviewed Publications*

**2024**

- **Razo-Mejia, M**., Mani, M. & Petrov, D. *Bayesian inference of relative
fitness on high-throughput pooled competition assays*. **PLoS Comp. Bio.**
(2023).
<a href="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011937">
open-access PDF
<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
</a> | 
<a href="https://mrazomej.github.io/bayesian_fitness/paper.html">
paper website
<i class="fa fa-window-restore" aria-hidden="true"></i>
</a> | 
<a href="https://github.com/mrazomej/bayesian_fitness/tree/master">
github repository
<i class="fa fa-github-square" aria-hidden="true"></i>
</a> | 
<a href="https://mrazomej.github.io/BarBay.jl/stable/">
BarBay.jl documentation
<i class="fa fa-laptop" aria-hidden="true"></i>
</a>

**2021**

- Morrison, M. J., **Razo-Mejia, M.** & Phillips, R. *Reconciling kinetic and
thermodynamic models of bacterial transcription*. PLoS Comp. Bio. (2021).
<a href="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008572">
open-access PDF
<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
</a> | 
<a href="https://github.com/RPGroup-PBoC/bursty_transcription">
github repository
<i class="fa fa-github-square" aria-hidden="true"></i>
</a>

**2020**

- **Razo-Mejia, M.** et al. *First-principles prediction of the information 
processing capacity of a simple genetic circuit*. Phys. Rev. E 102, 022404 
(2020). 
<a href="https://journals.aps.org/pre/abstract/10.1103/PhysRevE.102.022404">
open-access PDF
<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
</a> | 
<a href="https://www.rpgroup.caltech.edu/chann_cap/">
paper website
<i class="fa fa-window-restore" aria-hidden="true"></i>
</a> | 
<a href="https://github.com/RPGroup-PBoC/chann_cap">
github repository
<i class="fa fa-github-square" aria-hidden="true"></i>
</a>

**2019**

- Chure, G., **Razo-Mejia, M.**, et al. *Predictive shifts in free energy couple
mutations to their phenotypic consequences*. PNAS 201907869 (2019)
doi:10.1073/pnas.1907869116.
<a href="https://www.pnas.org/content/116/37/18275.short">
open-access PDF
<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
</a> | 
<a href="https://github.com/RPGroup-PBoC/mwc_mutants">
paper website
<i class="fa fa-window-restore" aria-hidden="true"></i>
</a> | 
<a href="https://github.com/RPGroup-PBoC/chann_cap">
github repository
<i class="fa fa-github-square" aria-hidden="true"></i>
</a>

- Phillips, R. Belliveau, N., Chure, G., Garcia, H., **Razo-Mejia, M.**, &
Scholes, Clarissa. *Figure 1 Theory Meets Figure 2 Experiments in the Study of
Gene Expression*. Annu. Rev. Biophys. 48, 121–163 (2019).
<a href="https://www.annualreviews.org/doi/abs/10.1146/annurev-biophys-052118-115525">
link
<i class="fa fa-external-link-square" aria-hidden="true"></i>
</a>

- Foster, P. J., **Razo-Mejia, M.** & Phillips, R. *Measuring the Energetic
Costs of Embryonic Development*. Dev. Cell 48, 591–592 (2019).
<a href="https://www.sciencedirect.com/science/article/pii/S153458071930139X">
link
<i class="fa fa-external-link-square" aria-hidden="true"></i>
</a>

**2018**

- **Razo-Mejia, M.** et al. *Tuning Transcriptional Regulation through
Signaling: A Predictive Theory of Allosteric Induction*. Cell Syst. 6,
456-469.e10 (2018). 
<a href="https://www.sciencedirect.com/science/article/pii/S2405471218300577">
open-access PDF
<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
</a> | 
<a href="http://www.rpgroup.caltech.edu/mwc_induction/">
paper website
<i class="fa fa-window-restore" aria-hidden="true"></i>
</a> | 
<a href="http://www.github.com/rpgroup-pboc/mwc_induction">
github repository
<i class="fa fa-github-square" aria-hidden="true"></i>
</a>

**2015**

- Zelcbuch, L., **Razo-Mejia, M.**, et al. *An In Vivo Metabolic Approach for
Deciphering the Product Specificity of Glycerate Kinase Proves that Both E.
coli’s Glycerate Kinases Generate 2-Phosphoglycerate*. PLoS One 10, e0122957
(2015).
<a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0122957">
open-access PDF
<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
</a>

**2014**

- **Razo-Mejia, M.** et al. *Comparison of the theoretical and real-world
evolutionary potential of a genetic circuit*. Phys. Biol. 11, 026005 (2014).
<a href="https://iopscience.iop.org/article/10.1088/1478-3975/11/2/026005">
link
<i class="fa fa-external-link-square" aria-hidden="true"></i>
</a>